remote_theme: just-the-docs/just-the-docs@v0.10.0
title: BBC 6 Minute English
description: BBC 6 Minute English 中英文对照学习资料
baseurl: "/bbc-6-minute-english"
url: "https://yourusername.github.io"

search_enabled: true

markdown: kramdown
kramdown:
  input: GFM

callouts:
  warning:
    title: WARNING               
    color: red

callouts:
  note:
    title: NOTE         
    color: purple

callouts:
  important:
    title: IMPORTANT         
    color: blue

callouts:
  new:
    title: NEW
    color: green

callouts:
  new:
    title: NEW
    color: green
